// LOCALHOST

### Retrieve data
GET http://localhost:3000/api/users HTTP/1.1
content-type: application/json

### Retrieve data
DELETE  http://localhost:3000/api/users/62889e3063c211e3967f1231 HTTP/1.1
content-type: application/json


### PUT contact (Update data)
POST http://localhost:3000/api/users/ HTTP/1.1
content-type: application/json

{
    "name": "Julia Lusamba Banyingela II",
    "email": "julia-der@gmail.com",
    "gender": "Female",
    "status": "Active",
}
 